server:
  port: 3000

db:
  type: 'mysql'
  # type: 'mariadb'
  port: 3306
  database: 'ddangddang'
  # database: 'moto4321'
  # database: 'nestjs'

map:
  kakaoBaseUrl: 'https://dapi.kakao.com/v2/local'
  kakaoApiKey: 'ec8e57794f4f7df81f1390c244b21390'
  josoConfirmKey: 'devU01TX0FVVEgyMDIyMDUwNzE0MjY0MTExMjUzODc='
  jusoBaseUrl: 'https://www.juso.go.kr/addrlink/addrLinkApi.do'

google:
  clientId: '498838057814-v2imn4kj4lqjdd1bn0hf8qd1t380p7g5.apps.googleusercontent.com'
  clientSecret: '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'
  callBackUrl: 'http://localhost:3005/api/players/googleauth'

kakao:
  clientId: 'b2003b9c5ce6789f9a92e48c92dfd182'
  clientSecret: 'hzVdVPWC40p4vAlfyWIWRgvngNw1Ro2Q'
  callBackUrl: 'http://localhost:3005/api/players/kakaoauth'

jwt:
  refreshTokenExp: 603800 
  refreshTokenSecret: 'ddongddong'
  accessTokenExp: 7200 
  accessTokenSecret: 'ddingdding'