db:
  host: 'localhost'
  username: 'root'
  password: 'Dntjr1357!'
  synchronize: true
  # host: 'diasm.mooo.com'
  # username: 'moto4321'
  # password: 'Abcde1234!@#$'
  # synchronize: true

jwt:
  accessSecret: 'ddingdding'
  refreshSecret: 'ddongddong'